apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-capsule
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: '>=v1.0.6'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the Capsule Helm chart with a minimal, stable interface.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-capsule
    Crossplane configuration that wraps the Capsule Helm chart for multi-tenancy.
  repository: ghcr.io/hops-ops/helm-capsule
  source: github.com/hops-ops/helm-capsule
